discord-net/Discord.Net

src/Discord.Net.Commands/CommandBuilder.cs, src/Discord.Net.Commands/CommandService.cs
Hopefully I set the PR up correctly this time.
The help command will now display top level commands and aliases, and will display subcommands and parameters for the requested command.
Also changed the order of commands/aliases being added, and removed a duplicate adding of commands.
=> Help command changes

src/Discord.Net/DiscordConfig.cs
fixes avatar URLs downloading properly
=> Remove the trailing slash on the CDN URL in DiscordConfig

src/Discord.Net/Models/Server.cs
Removed the exception because it will default to text if not specified, and it already was an optional parameter, which didn't make sense if its going to throw on null.
Hopefuly i got the PR right this time.
=> Removed ArgumentNullException from FindChannels

docs/features/management.rst, docs/features/server-management.rst, docs/features/user-management.rst, docs/index.rst, test/Discord.Net.Tests/Discord.Net.Tests.csproj, test/Discord.Net.Tests/Tests.cs, test/Discord.Net.Tests/packages.config
Reference Pull #36, amended the commit to include the new documentation pages.
=> [docs] split management into server- and user-; wrote docs for server/user

src/Discord.Net.Audio/Net/VoiceSocket.cs, src/Discord.Net/DiscordClient.cs
- Voice connection no longer throws an error if there is no "?" in the Host string.
- Resetting the counter and clearing the array of large servers. (in order to get them all, not just first 50)
- Moved counter check for large servers before dequeuing the server. (like this you won't skip every 50th server, since it will dequeue first and check later right now)
Managed to get my bot working with these changes, although after some time I get 4003 and unknown opcode 9 errors (probably unrelated to this)
=>  Voice crashfix, Properly getting data for large servers.

src/Discord.Net/API/Client/Common/UserReference.cs, src/Discord.Net/Models/User.cs, src/Discord.Net/project.json
A few users requested an IsBot field for marking Bot Accounts;
Bumping Version number because it has been 0.9-rc3 forever and that's caused a bit of confusion in the channel with what version users are on.
=> Add `User.IsBot` field, bump version number to 0.9.1

src/Discord.Net/API/Client/Common/Role.cs, src/Discord.Net/API/Client/Rest/UpdateRole.cs, src/Discord.Net/Models/Message.cs, src/Discord.Net/Models/Role.cs, src/Discord.Net/Models/Server.cs
`Message.MentionedRoles` is now populated properly with roles.
`Role.IsMentionable` has been added to determine whether
`Role.Mention` now mentions roles that are `IsMentionable` as expected (otherwise returns empty string)
`Role.Edit` now takes parameter `bool? isMentionable`
`Server.CreateRole` now takes parameter `bool isMentionable`
`IsMentionable` added to `UpdateRoleRequest`
=> Support Role Mentions

src/Discord.Net.Commands/CommandService.cs, src/Discord.Net.Commands/CommandServiceConfig.cs
Adds `CommandConfigBuilder.IsSelfBot`, default as false
When true, the bot ignores everyone but itself, as far as commands. This is the behavior expected of SelfBots, as inferred from the Discord stance.
=> Added SelfBot Functionality by Config

src/Discord.Net/Models/Channel.cs
Added OutOfBounds exception for DeleteMessages, for when Message Count is less than 2 or greater than 100
=> BulkMessageDelete Exception

src/Discord.Net/Entities/WebSocket/MessageManager.cs
Downloading Messages from a DM Channel was causing a cast on Line 64 to throw a nullref.
=> Add null-conditional to MessageManager

src/Discord.Net.Commands/Attributes/ModuleAttribute.cs, src/Discord.Net.Commands/CommandService.cs, src/Discord.Net.Commands/Dependencies/DependencyMap.cs, src/Discord.Net.Commands/Dependencies/IDependencyMap.cs, src/Discord.Net.Commands/Module.cs, src/Discord.Net.Commands/ReflectionUtils.cs
Resolves #128 and improves on foxbot's existing code.
Modules can now be constructed using something like this:
```cs
public Module(ClassA a, ClassB b, CommandService service) { }
```
If the code has any other parameters other than CommandService, a DependencyMap is required to be passed to LoadAssembly; otherwise the code will throw an exception stating that dependency injection is required.
=> Add Dependency Injection and Autoloading to the Commands service

src/Discord.Net.Commands/ReflectionUtils.cs
This should allow modules with static fields (e.g. in place of constants for types which cannot be marked 'constant') to work without an exception being thrown.
=> Ignore static constructors when creating types

src/Discord.Net/DiscordSocketClient.cs
This gateway event is raised when a message in a GuildChannel is pinned or unpinned. Unfortunately, this event only contains a timestamp of when the pin was changed, making it effectively useless. As a result, it will be dropped.
Resolves #135
=> Ignore CHANNEL_PINS_UPDATE

src/Discord.Net/API/Common/Invite.cs, src/Discord.Net/API/DiscordRestApiClient.cs, src/Discord.Net/API/Rest/CreateChannelInviteParams.cs, src/Discord.Net/Entities/Channels/IGuildChannel.cs, src/Discord.Net/Entities/Guilds/IGuild.cs, src/Discord.Net/Entities/Invites/IInvite.cs, src/Discord.Net/IDiscordClient.cs, src/Discord.Net/Rest/DiscordRestClient.cs, src/Discord.Net/Rest/Entities/Channels/GuildChannel.cs, src/Discord.Net/Rest/Entities/Guilds/Guild.cs, src/Discord.Net/Rest/Entities/Invites/Invite.cs
Resolves #153
This is a breaking change!
With the introduction of Vanity URLs and the shortening of Invite URLs, the API appears to have removed the "xkcdpass" field of the Invite. 
Since this functionality was removed from the Discord API and thus obsolete, it has been removed from the Invite models.
=> Remove all references to XKCD URLs in Invites

src/Discord.Net.Commands/Attributes/DescriptionAttribute.cs, src/Discord.Net.Commands/Command.cs
Added `Command.Synopsis` for separation of short and long descriptions, this being intended for long.
=> Added `Command.Synopsis`

src/Discord.Net.Commands/CommandService.cs
Resolves #160.
Previously, if a user autoloaded commands more than once, commands that were already in the command map would be readded. 
If the module list already contains a module with the same type as the module being loaded, it will not load the new instance of this module.
=> Don't load modules that are already loaded

src/Discord.Net/WebSocket/Entities/Users/SocketSelfUser.cs
Resolves #159.
The previous bug was that SocketSelfUser did not inherit from ISelfUser, so DiscordSocketClient.GetCurrentUserAsync was not returning a SocketSelfUser, despite the underlying type being that. This caused ModifyStatusAsync to throw the NotSupportedException that existed on the REST SelfUser.
=> SocketSelfUser inherits ISelfUser

src/Discord.Net/API/DiscordRestApiClient.cs, src/Discord.Net/Entities/Channels/IMessageChannel.cs, src/Discord.Net/Rest/Entities/Channels/DMChannel.cs, src/Discord.Net/Rest/Entities/Channels/GroupChannel.cs, src/Discord.Net/Rest/Entities/Channels/TextChannel.cs
Resolves #168.
This commit adds GET /channels/{id}/pins to the ApiClient, and adds GetPinnedMessagesAsync to IMessageChannel. This method is only implemented on the REST entities, and the WebSocket entities do not include an override to retrieve pinned messages from cache.
=> Support GET /channels/{id}/pins

src/Discord.Net.Net45/Discord.Net.csproj, src/Discord.Net.Net45/Enums/TokenType.cs, src/Discord.Net/DiscordClient.cs
Basically grabbed this from 1.0, thank you Rand for all the help
=> Added bot authorization headers

src/Discord.Net/Rest/Entities/Guilds/Guild.cs
... instead of AddBanAsync(ulong,int)
Fixes StackOverflowException which occurs when AddBanAsync is called.
=> Fixed AddBanAsync(IUser,int) calling itself

src/Discord.Net.Commands/CommandParser.cs
paramList was being passed as null, which caused an exception when `ParseResult.FromSuccess` tried looping through it
=> Fixed NullRef

src/Discord.Net/Format.cs
Resolves #249 
Automatically escaping in the individual formatting methods would be a bad idea because it would prevent chaining, e.g:
```cs
var message = $"Tried to ban user {Format.Bold(Format.Italics(user.Name))}";
```
Instead, the developer should be escaping manually, like so:
```cs
var message = $"Tried to ban user {Format.Bold(Format.Italics(Format.Sanitize(user.Name)))}";
```
=> Add Sanitize function to escape Markdown

src/Discord.Net/API/Client/GatewaySocket/Commands/Identify.cs, src/Discord.Net/DiscordConfig.cs, src/Discord.Net/Net/Rest/RestClient.cs, src/Discord.Net/Net/WebSockets/GatewaySocket.cs
Keeping it simple; didn't backport optional params from 1.0.
hammerandchisel/discord-api-docs#17
=> Adds sharding support

src/Discord.Net/WebSocket/DiscordSocketClient.cs
This is the way MessageDeleted works. Just making it consistent.
Right now, first argument is always returning true on IsSpecified with null as the value if message isn't in the cache. With this fix will return IsSpecified=false when it is null.
=> Fixed Optional argument in Message Updated event

src/Discord.Net.Core/Entities/Messages/IMessage.cs, src/Discord.Net.Core/Entities/Messages/IUserMessage.cs
Was originally an issue due to a bug that prevented deletion of System Messages. Bug has since been resolved.
=> Moved IDeletable interface up inheritance to IMessage

src/Discord.Net.Rest/Entities/Guilds/GuildHelper.cs, src/Discord.Net.Rest/Entities/Guilds/RestGuild.cs, src/Discord.Net.Rest/Entities/Roles/RestRole.cs
Solves Issue #342 , but there might be a cleaner way to do this that doesn't make you end up with a IGuild in the RestRole that might return a SocketGuild or a RestGuild depending on your DiscordClient.
The other option I can see is to DI the guild.Id into role.ModifyAsync, but then you still end up with an empty RestGuild field in the RestRole object.
Suggestions greatly appreciated.
=> Fix nullref during CreateRoleAsync

src/Discord.Net.Core/Entities/Roles/IRole.cs, src/Discord.Net.Core/Entities/Users/IGuildUser.cs, src/Discord.Net.Core/Extensions/GuildUserExtensions.cs, src/Discord.Net.Core/Extensions/RoleExtensions.cs, src/Discord.Net.Rest/Entities/Roles/RestRole.cs, src/Discord.Net.Rest/Entities/Users/RestGuildUser.cs, src/Discord.Net.WebSocket/Entities/Roles/SocketRole.cs, src/Discord.Net.WebSocket/Entities/Users/SocketGuildUser.cs
Allows GuildUsers and Roles to be compared with each other in a reasonable manner. Addresses the issue mentioned in #248.
=> Implement IComparable<T> on IRole, add extension IRole#CompareTo

src/Discord.Net.Commands/Readers/EnumTypeReader.cs
Enumerating over the Enum values would prevent declarations such as this: `enum Foo {A, B, AliasForA = A}` from being parsed properly as AliasForA would not be contained within _enumsByName. By all means, if there's a cleaner implementation rather than having to check if _enumsByValue already contains the key, spruce up my changes.
Also opted to have the error message say exactly which parse failed.
=> Fix EnumTypeReader missing equivalent Enum values by name.

src/Discord.Net.Commands/ModuleBase.cs, src/Discord.Net.Core/API/Common/Embed.cs, src/Discord.Net.Core/API/Common/EmbedAuthor.cs, src/Discord.Net.Core/API/Common/EmbedField.cs, src/Discord.Net.Core/API/Common/EmbedFooter.cs, src/Discord.Net.Core/API/DiscordRestApiClient.cs, src/Discord.Net.Core/API/Rest/CreateMessageParams.cs, src/Discord.Net.Core/Entities/Channels/IMessageChannel.cs, src/Discord.Net.Core/Entities/Messages/EmbedAuthor.cs, src/Discord.Net.Core/Entities/Messages/EmbedField.cs, src/Discord.Net.Core/Entities/Messages/EmbedFooter.cs, src/Discord.Net.Core/Entities/Messages/IEmbed.cs, src/Discord.Net.Core/Utils/EmbedBuilder.cs, src/Discord.Net.Rest/Entities/Channels/ChannelHelper.cs, src/Discord.Net.Rest/Entities/Channels/IRestMessageChannel.cs, src/Discord.Net.Rest/Entities/Channels/RestDMChannel.cs, src/Discord.Net.Rest/Entities/Channels/RestGroupChannel.cs, src/Discord.Net.Rest/Entities/Channels/RestTextChannel.cs, src/Discord.Net.Rest/Entities/Channels/RestVirtualMessageChannel.cs, src/Discord.Net.Rest/Entities/Messages/Embed.cs, src/Discord.Net.Rpc/Entities/Channels/RpcDMChannel.cs, src/Discord.Net.Rpc/Entities/Channels/RpcGroupChannel.cs, src/Discord.Net.Rpc/Entities/Channels/RpcTextChannel.cs, src/Discord.Net.WebSocket/Entities/Channels/ISocketMessageChannel.cs, src/Discord.Net.WebSocket/Entities/Channels/SocketDMChannel.cs, src/Discord.Net.WebSocket/Entities/Channels/SocketGroupChannel.cs, src/Discord.Net.WebSocket/Entities/Channels/SocketTextChannel.cs
This PR adds support for Rich Embeds.
**This can be a breaking change!**
The `IMessageChannel.SendMessage` method has been modified to include an optional `API.Embed` parameter, which will be sent to Discord with the message. You can produce an `API.Embed` object through the `EmbedBuilder` utility, or by creating it yourself.
This feature has been tested.
Since, with this update, messages no longer need to have any content to be valid, I have removed any preconditions that ensure messages have content. However, **sending messages with no content will crash the ratelimiter.** Still looking into a cause.
=> Support rich Embeds

src/Discord.Net/API/Client/GatewaySocket/Commands/Identify.cs, src/Discord.Net/API/Client/GatewaySocket/OpCodes.cs, src/Discord.Net/Net/WebSockets/GatewaySocket.cs
The problem seemed to be that adding the `shards` field in your IDENTIFY payload with a user token would cause the api to return an OP code 9.
Should fix #349 too.
=> Fixed connecting with user tokens and updated gateway OP codes

src/Discord.Net.Commands/CommandParser.cs
A simple fix for #262. The problem was that `curPart` was never reset to `ParserPart.None` when reading a parameter with IsMultiple, so the parser would throw an error when it found `ParserPart.QuotedParameter` at the end of the parsing.
The solution is to always reset `curPart` to `ParserPart.None` and not reset `curParam` to `null` when reading a IsMultiple parameter. That way we can check if `curParam` is `null` before beginning a new parameter.
I've tested this solution with multiple parameter and input combinations and haven't found any problems.
=> Fix parsing of quoted parameters in params arguments (Fix #262)

src/Discord.Net.Core/API/Common/Embed.cs, src/Discord.Net.Core/API/Common/EmbedImage.cs, src/Discord.Net.Core/API/Common/EmbedVideo.cs, src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs, src/Discord.Net.Core/Entities/Messages/EmbedImage.cs, src/Discord.Net.Core/Entities/Messages/EmbedThumbnail.cs, src/Discord.Net.Core/Entities/Messages/EmbedVideo.cs, src/Discord.Net.Core/Entities/Messages/IEmbed.cs, src/Discord.Net.Rest/Entities/Messages/Embed.cs
Adds builders for Thumbnail and Image embeds as well as JSON models for Video and Image embeds as per https://discordapp.com/developers/docs/resources/channel#embed-object . Not sure if I should keep the Height and Width parameters as they are currently ignored by discord as far as I can tell.
=> Builders for Thumbnail and Image embeds

src/Discord.Net.Commands/Attributes/CommandAttribute.cs, src/Discord.Net.Commands/Builders/CommandBuilder.cs, src/Discord.Net.Commands/CommandService.cs, src/Discord.Net.Commands/CommandServiceConfig.cs, src/Discord.Net.Commands/Info/CommandInfo.cs
This adds an (optional) CommandServiceConfig, as well as a DefaultRunMode for commands.
This resolves #368 (for commands where a RunMode is not explicitly specified, a custom default value should be used)
=> Add CommandServiceConfig, DefaultRunMode

src/Discord.Net.Core/API/DiscordRestApiClient.cs, src/Discord.Net.Core/API/Rest/ModifyMessageParams.cs, src/Discord.Net.Core/Entities/Messages/IUserMessage.cs, src/Discord.Net.Core/Entities/Messages/ModifyMessageParams.cs, src/Discord.Net.Rest/Entities/Messages/MessageHelper.cs
**This is not a breaking change**.
This change begins to implement #379, where IUserMessage.ModifyAsync will now accept a `Discord.ModifyMessageParams` func over a `Discord.API.Rest.ModifyMessageParams` func.
=> ModifyAsync will accept an EmbedBuilder

src/Discord.Net.Commands/CommandService.cs, src/Discord.Net.Commands/PrimitiveParsers.cs
Added a TimeSpan TypeReader. Useful for taking in a measure of time for a command (i.e. a temporary ban).
=> Add TimeSpan TypeReader

src/Discord.Net.Core/Entities/Messages/EmbedBuilder.cs
This is arguably the silliest Pull Request. But better than just whining about it.
=> EmbedBuilder.WithImageUrl() now uses the value passed

docs/guides/samples/command_handler.cs
if (!result.IsSuccess)
await msg.Channel.SendMessageAsync(result.ErrorReason);
}
msg -> context
=> Fixed HandleCommand Error message

src/Discord.Net/Net/Rest/BuiltInEngine.cs
Fixed `BuiltInEngine.SendFile()` method. `StreamContent` was creating `FileStream` from path resulting in error. Path in this method is filename with extension, so just used already created stream for requested file.
As I'm porting old bot as `netcoreapp1.0` already tested on `win10` and `debian8`, works just fine.
Also, when I first tried to send file, there was another error in https://github.com/Grimitsu/Discord.Net/blob/master/src/Discord.Net/Net/WebSockets/BuiltInEngine.cs#L68
Maybe it just me, but fixed this upgrading .NETLibrary to 1.6.1.
Would be good if anyone could reproduce it, cause I don't get a word about `MemoryStream` at least if adding `Discord.Net` as nuget package.
Consider updating reference to `.NetLibrary`.
=> Fix BuildInEngine.SendFile() error and suggestion to possible issue.
