- README.md
Changed the documentation to reflect the right version number and to prevent confusion. Changed from 0.8.0-beta1 to 0.8.1-beta.
> Changed the dev branch version number

- docs/features/events.rst
- docs/features/permissions.rst
- docs/global.txt
- docs/samples/events.cs
- docs/samples/permissions.cs
global: Modified the unicode in |stub| to be compatible with sphinx. Still appears as a wrench in the browser.
events: added information for events, and a list of events, as well as their arg paramater. Still marked as 'WIP', as I feel my documentation was a bit lacking
permissions: added information for channel\server permissions, dual channel permissions, and roles. need to update with bits at some point.
> Updated the Documentation

- docs/samples/getting_started.cs
Changed DiscordBotClient to DiscordClient.
changed MessageReived to messageCreated.
Changed Send Message to now take a channel, rather than ID.
Changed Accept invite.
> Updated getting_started.cs so that it works on 0.8.1

- src/Discord.Net/Models/Message.cs
Or you'll get an overflow error!
> Use `ulong` instead of `long` to store message id

- docs/features/commands.rst
- docs/features/events.rst
- docs/features/permissions.rst
- docs/index.rst
- docs/samples/getting_started.cs
- docs/samples/permissions.cs
Began updating documentation; fixed features/permissions to use more up-to-date information; made features/events contain usable information (removed the table of events); marked commands as a stub due to it being outdated; modified samples; updated index page
requesting to merge into dev for now because git confuses me and I built my new changes off of dev
> started updating documentation for 0.9

- docs/features/logging.rst
- docs/features/profile.rst
- docs/samples/logging.cs
remove obsoleted profile page; update features/logging, remove it from stub; update logging example
> updated documentation to include new logging system

- src/Discord.Net.Commands/CommandService.cs
- src/Discord.Net.Commands/CommandServiceConfig.cs
Finally removed the placeholders...
> Change built in help & Custom command activation

- src/Discord.Net/Models/Server.cs
Small fix to return the correct server icon url
> Fix Server GetIconUrl string

- src/Discord.Net.Audio/AudioClient.cs
- src/Discord.Net.Audio/AudioService.cs
Code now assumes client is logged in as Bot Account, without 1 voice channel limit
> Removed hack

- src/Discord.Net.Net45/API/Client/Rest/UpdateOwnNick.cs
- src/Discord.Net.Net45/Discord.Net.csproj
- src/Discord.Net/API/Client/Rest/UpdateMember.cs
- src/Discord.Net/Models/User.cs
```cs
User.Edit(nickname: "foo");
```
> Add support for changing Nicknames!

- README.md
also changed the badges to be 200% more pretty
> Update docs link in README to legacy

- src/Discord.Net/API/DiscordAPIClient.cs
- src/Discord.Net/API/Rest/GetGuildMembersParams.cs
- src/Discord.Net/Entities/Channels/DMChannel.cs
- src/Discord.Net/Entities/Channels/GuildChannel.cs
- src/Discord.Net/Entities/Channels/IChannel.cs
- src/Discord.Net/Entities/Channels/TextChannel.cs
- src/Discord.Net/Entities/Channels/VoiceChannel.cs
- src/Discord.Net/Entities/Guilds/Guild.cs
- src/Discord.Net/Entities/WebSocket/CachedDMChannel.cs
- src/Discord.Net/Entities/WebSocket/CachedGuild.cs
- src/Discord.Net/Entities/WebSocket/CachedTextChannel.cs
- src/Discord.Net/Entities/WebSocket/CachedVoiceChannel.cs
See: https://github.com/hammerandchisel/discord-api-docs/issues/82
> Update GetGuildMembersAsync, remove paginated GetUsersAsync.

- src/Discord.Net/DiscordClient.Events.cs
Added XML Doc summaries to the Client Events to help users of the library decide which events to use. Based off of [event descriptions in the Discord API](https://discordapp.com/developers/docs/topics/gateway)
> Added XML Doc summaries to the Client Events

- src/Discord.Net/Entities/Roles/Color.cs
> Added ToString and DebuggerDisplay

- src/Discord.Net.Commands/Command.cs
- src/Discord.Net.Commands/Readers/EnumTypeReader.cs
Added Dynamic Enum TypeParsing. Parser will now detect if a Parameter type is an Enum and dynamically create a TypeParser for it.
> Enum TypeReader

- src/Discord.Net/WebSocket/Extensions/ChannelExtensions.cs
- src/Discord.Net/WebSocket/Extensions/GuildExtensions.cs
Resolves #146.
Adds extension methods to `IGuildChannel` and `IChannel` types for WebSocket users.
> Added Extension Methods for WebSocket

- src/Discord.Net/WebSocket/Entities/Channels/SocketVoiceChannel.cs
- src/Discord.Net/WebSocket/Entities/Guilds/SocketGuild.cs
This implements the Promise we were talking about and allows an AudioClient to successfully connect.
> Finish SocketVoiceChannel.ConnectAsync

- src/Discord.Net/DiscordConfig.cs
> Fixed the CDN url

- src/Discord.Net.Commands/Attributes/DescriptionAttribute.cs
- src/Discord.Net.Commands/Command.cs
- src/Discord.Net.Commands/CommandParameter.cs
- src/Discord.Net.Commands/CommandService.cs
- src/Discord.Net.Commands/Module.cs
Most of these tweaks make documentation of commands easier for bot developers who want to do things their own way.
> Command tweaks

- src/Discord.Net/WebSocket/Extensions/SocketClientExtensions.cs
> Add Sync Extensions for DiscordSocketClient

- src/Discord.Net.Commands/Attributes/NameAttribute.cs
- src/Discord.Net.Commands/Command.cs
- src/Discord.Net.Commands/Module.cs
> Add NameAttribute for overriding Name in commands/modules

- src/Discord.Net.Commands/Module.cs
> Add Prefix property to Module

- src/Discord.Net/Rest/Entities/Channels/DMChannel.cs
- src/Discord.Net/Rest/Entities/Channels/GroupChannel.cs
- src/Discord.Net/Rest/Entities/Channels/TextChannel.cs
Should be tested though, since Khio says it is working properly anyway, which doesn't seem possible.
> Proper implementation of GetMessagesAsync, fixes #201 ?

- src/Discord.Net/WebSocket/Entities/Users/SocketGuildUser.cs
This fix the VoiceChannel being null.
> Fix Voice Channel being null #174

- src/Discord.Net.Commands/Attributes/AliasAttribute.cs
- src/Discord.Net.Commands/Command.cs
- src/Discord.Net.Commands/Map/CommandMap.cs
This implementation could probably be more efficient, but I opted for clarity and simplicity where possible.
> Implement Command Aliases

- src/Discord.Net.Commands/Map/CommandMap.cs
> Fix command aliases (#244)

- src/Discord.Net.Commands/CommandParser.cs
Looks like some logic was getting triggered when it shouldn't have been.
> Resolve #251

- src/Discord.Net.Commands/Command.cs
- src/Discord.Net.Commands/Module.cs
Resolves #253 and works correctly with aliases/etc.
> Allow parameterless commands to build correctly

- src/Discord.Net/project.json
Applies https://github.com/RogueException/Discord.Net/commit/ed7710fbef94ebc0a561b2d4a682026b2ffdad59 to the main project as well as the commands namespace
> Optimize rest of lib for release builds

- src/Discord.Net/WebSocket/DiscordSocketClient.cs
- src/Discord.Net/WebSocket/Entities/Guilds/SocketGuild.cs
Kwoth asked Foxbot who asked me to add a this line into the ChannelCreated event.
> Fixed ChannelCreated event not triggering

- src/Discord.Net.Commands/Attributes/RemarksAttribute.cs
- src/Discord.Net.Commands/Attributes/SummaryAttribute.cs
- src/Discord.Net.Commands/Command.cs
- src/Discord.Net.Commands/Module.cs
> Rename Cosmetic Command Attributes to Summary/Remarks

- docs/migrating.md
> Slight singular word spelling

- src/Discord.Net/Entities/Users/UserStatus.cs
- src/Discord.Net/Net/Converters/UserStatusConverter.cs
This should be all the references to UserStatus. Added DoNotDisturb after Offline to hopefully break as little bots as possible.
> Added support for Do Not Disturb UserStatus

- src/Discord.Net.Core/API/DiscordRestApiClient.cs
> Adjusted GetGuildPruneCount to using params;

- src/Discord.Net.Commands/ModuleBase.cs
> Update ReplyAsync Task to return the sent message.

- src/Discord.Net.Core/Net/Queue/RequestQueueBucket.cs
- src/Discord.Net.Core/Net/Rest/DefaultRestClient.cs
Sometimes "Date" is "date". This fixes it.
> Make header dictionary ignore case

- docs/guides/samples.md
- docs/guides/samples/faq/status.cs
Updated the _Modify Status_ sample  to reflect code changes in 043f8ded85654ec5c2bf607ba7fddcc1050f167f
Was already noticed in RogueException/Discord.Net#347, but got closed without an update in the doc
> Doc update for modify user sample code

- src/Discord.Net.Commands/Readers/EnumTypeReader.cs
Whoopsie. I even tested before and didn't have this error show up. /shrug
> Values in ImmutableDictionaries were strings rather than enumType

- docs/guides/samples/dependency_map_setup.cs
await commands.LoadAssembly(Assembly.GetCurrentAssembly(), map);
->
await commands.AddModulesAsync(Assembly.GetEntryAssembly());
> Fixed Install -> commands.LoadAssembly

- docs/guides/samples/require_owner.cs
CheckPermissions was not set to async so await would not work.
> Fixed async method

- src/Discord.Net.Rest/DiscordRestClient.cs
- src/Discord.Net.Rest/Entities/Messages/MessageHelper.cs
- Added methods to add & remove reactions without needing a message instance
- Useful for Pagination without needing the Paginator message in Cache
> Add methods to interact with reactions without a message instance
